artifact_location: file:///d:/ML Projects/KidneyDiseaseDL/KidneyDiseaseEndtoEndDL/your-mlflow-uri/0
creation_time: 1753687513616
experiment_id: '0'
last_update_time: 1753687513616
lifecycle_stage: active
name: Default
