artifact_uri: file:///d:/ML Projects/KidneyDiseaseDL/KidneyDiseaseEndtoEndDL/your-mlflow-uri/0/8a6904c1251f4ce183e03c03a7c7c0be/artifacts
end_time: 1753687513686
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 8a6904c1251f4ce183e03c03a7c7c0be
run_name: youthful-fly-585
run_uuid: 8a6904c1251f4ce183e03c03a7c7c0be
source_name: ''
source_type: 4
source_version: ''
start_time: 1753687513627
status: 3
tags: []
user_id: anujayavidmal2002
